config/routes.rb
UrlShortner::Application.routes.draw do
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :sessions  
  resources :users do
    resources :urls
  end
  
  root :to => 'users#new'

  match "/:short_url" => 'urls#go_to_url'
  
  

end

app/models/url.rb
class Url < ActiveRecord::Base
  attr_accessible :original_url, :short_url
  
  belongs_to :user
  
  # validates :original_url, :presence => true, :uniqueness => true, :format => {:with => /^(http:\/\/|https:\/\/)/}
  # validates :short_url, :presence => true, :uniqueness => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password, :password_confirmation
  
  has_many :urls
  
  validates_presence_of :password, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      puts "**********************************"
      # redirect_to user, :notice => "Logged in!"
      # redirect_to new_user_url_path, :notice => "Logged in!"
      redirect_to :controller => 'users', :action => 'index', :id => user.id
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
  
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  
  def index
    @urls = Url.all
  end
  
  def new
    @url = Url.new
  end
  
  def create
    @user = User.find(params[:user_id])
    # @url = @user.urls.build(params[:url])
    
    if params[:url][:short_url] == ""
      @url = @user.urls.build(:original_url => params[:url][:original_url],
                              :short_url => short_url(params[:url][:original_url]))
    else
      @url = @user.urls.build(:original_url => params[:url][:original_url],
                             :short_url => params[:url][:short_url])
    end
    
    if @url.save
      # redirect_to @user
      # redirect_to urls_path
      redirect_to :controller => 'users', :action => 'index', :id => @user.id
    else
      redirect_to user_urls_path
    end
    
    # # @url = Url.new(params[:url])
    # if params[:url][:short_url] == ""
    #   @url = Url.new(:original_url => params[:url][:original_url],
    #                  :short_url => short_url(params[:url][:original_url]))
    # else
    #   @url = Url.new(:original_url => params[:url][:original_url],
    #                  :short_url => params[:url][:short_url])
    # end
    # 
    # if @url.save
    #   redirect_to @url
    #   # redirect_to urls_path
    # else
    #   redirect_to new_user_url_path
    # end
  end
  
  def show
    # @url = Url.find_by_id(params[:id])
    @url = Url.find(params[:id])
  end
  
  def go_to_url
    @url = Url.find_by_short_url!(params[:short_url])
    @url.count += 1
    @url.save
    redirect_to @url.original_url
  end
    
  
  private
  
  def short_url(long_url)
    (('a'..'z').to_a + ('A'..'Z').to_a + (1..9).to_a).shuffle[0..5].join
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to login_path, :notice => "signed up!"
    else
      render "new"
    end
  end
  
  def show
    @user = User.find(params[:id])
    render "index"
  end
  
  def index
    @user = User.find(params[:id])
    @urls = Url.find_all_by_user_id(@user.id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortner</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<!-- <%= debug params %> -->
<%= link_to "logout", logout_path %>
</body>
</html>

app/views/urls/index.html.erb
<h2>URL Shortener Index</h2>

<p><%= link_to 'Create New URL', new_url_path %></p>

<table border="0">
	<tr>
		<td width="50" align="left">Visits</td>
		<td width="200">Short URL</td>
		<td width="200">Original URL</td>
	<tr>
<% @urls.each do |url| %>
	<tr>
		<td width="50" align="center"><%= url.count %></td>
		<!-- <td width="200"><a href="<%= url.short_url %>" target="_blank">localhost:3000/<%= url.short_url %></a></td> -->
		<td width="200"><%= link_to "http://localhost:3000/#{url.short_url}", "http://localhost:3000/#{url.short_url}", :target => "_blank" %></a></td>
		<td width="500"><%= url.original_url%></td>
	<tr>
<% end %>
</table>
	

app/views/urls/new.html.erb
<!-- <h2>URL To Shorten</h2>

<%= form_for @url do |f| %>

	<!-- <% if @url.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@url.errors.count, "error") %> prohibited this article from being saved:</h2>

	    <ul>
	    <% @url.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	<% end %> -->


	<%= f.label "Original URL:" %>
	<%= f.text_field :original_url , :value => "http://"%>
	<%= f.submit "Shorten URL" %><br>
	<%= f.label "Vanity URL:  " %>
	<%= f.text_field :short_url %>
	<%= f.label "(optional)" %>
<% end %>

<p><%= link_to 'See current URLs', urls_path %></p> -->

app/views/urls/show.html.erb
<!-- <h2>Shortened URL</h2>

<table border="0">
	<tr>
		<td width="200">Short URL</td>
		<td width="200">Original URL</td>
	<tr>
	<tr>
		<!-- <td width="200">localhost:3000/<%= @url.short_url %></a></td> -->
		<td width="200"><%= link_to "http://localhost:3000/#{@url.short_url}", "http://localhost:3000/#{@url.short_url}", :target => "_blank" %></td>
		<td width="200"><%= @url.original_url%></td>
	<tr>
</table>


<p><%= link_to 'Create New URL', new_url_path %></p>

<p><%= link_to 'See current URLs', urls_path %></p> -->

app/views/users/index.html.erb
<h2>User Index</h2>

<h3>Create A Link</h3>
<%= form_for [@user, @url = Url.new] do |f| %>
	<%= f.label "Original URL:" %>
	<%= f.text_field :original_url , :value => "http://"%>
	<%= f.submit "Shorten URL" %><br>
	<%= f.label "Vanity URL:  " %>
	<%= f.text_field :short_url %>
	<%= f.label "(optional)" %>
<% end %>

<h3>Existing Links</h3>
<table border="0">
	<tr>
		<td width="50" align="left">Visits</td>
		<td width="200">Short URL</td>
		<td width="200">Original URL</td>
	<tr>
<% @urls.each do |url| %>
	<tr>
		<td width="50" align="center"><%= url.count %></td>
		<!-- <td width="200"><a href="<%= url.short_url %>" target="_blank">localhost:3000/<%= url.short_url %></a></td> -->
		<td width="200"><%= link_to "http://localhost:3000/#{url.short_url}", "http://localhost:3000/#{url.short_url}", :target => "_blank" %></a></td>
		<td width="500"><%= url.original_url%></td>
	<tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :email %><br>
		<%= f.text_field :email %><br>
	</div>
	<div class="field">
		<%= f.label :password %><br>
		<%= f.password_field :password %><br>
	</div>
	<div>
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %><br>
	</div>
	<div class="actions"><%= f.submit %></div>
<% end %>

<%= link_to "Login", login_path %>

app/views/users/show.html.erb
<!-- <h2>User List</h2>

<%= form_for [@user, @url = Url.new] do |f| %>
	<%= f.label "Original URL:" %>
	<%= f.text_field :original_url , :value => "http://"%>
	<%= f.submit "Shorten URL" %><br>
	<%= f.label "Vanity URL:  " %>
	<%= f.text_field :short_url %>
	<%= f.label "(optional)" %>
<% end %>
 -->